== Comprehension

* 리스트에 기반한 객체(list, dictionary, set 등)를 만들기 위한 문법 구조
* Python 자료구조에 데이터를 효율적이고 간결하게 표현하기 위한 문법

[source, python]
----
lst = [x for x in range(1, 11) if x % 2 == 0]
----

---

Comprehension은 리스트에 기반한 객체들을 쉽게 만들기 위한 문법 구조입니다. 리스트에 기반한 자료구조는 다른 프로그래밍 언어의 배열과 유사한 선형 자료구조들로서, Python에서는 list, dictionary, set등을 의미합니다. 

Python에서 1에서 10까지의 정수 값들을 요소로 가지는 list를 생성하려면 아래와 같은 코드를 사용할 수 있습니다.

[source, python]
----
lst = []
for i in range(1, 11):
    lst.append(i)
----

Comprehension을 사용하면 아래와 같은 코드로 1에서 10까지의 정수 값들을 요소로 가지는 list를 만들 수 있습니다.

[source, python]
----
lst = [x for x in range(1, 11)]
----

Comprehension의 문법은 아래와 같습니다.

[source, python]
----
[( 변수를 활용한 값 ) for ( 사용할 변수 이름 ) in ( 순회할 수 있는 값 ) if 조건식]
----

== 중복 표현

Comprehension은 내부에서 for 키워드와 if 키워드를 반복하여 사용할 수 있습니다. 아래 코드는 두 list 객체를 사용하여 tuple들을 요소로 가지는 list 타입 객체를 생성합니다. Comprehension은 다중 루프와 동일하게 동작합니다. 아래 코드는 구구단의 표현할 수 있는 리스트를 만듭니다.

[source, python]
----
table = [x for x in range(2, 10)]
numbers = [x for x in range(1, 10)]

mtable = [(x, y * x) for x in table for y in numbers]
----

== list compression

list compreshension은 list 타입 객체를 생성하는 Python 문법입니다. list compression은 list를 생성하여 return 하므로 대괄호( [ ] )를 사용합니다.

아래 코드는 1에서 20까지의 정수 중 음수만을 요소로 가지는 list 타입 객체를 생성합니다.

[source, python]
----
lst = [x for x in range(1, 21) if x % 2 != 0]
----

== set comprehension

set compreshension은 list 타입 객체를 생성하는 Python 문법입니다. set compression은 set를 생성하여 return 하므로 중괄호( { } )를 사용합니다.

아래 코드는 1에서 20까지의 정수 중 음수만을 요소로 가지는 set 타입 객체를 생성합니다.

[source, python]
----
s = {x for x in range(1, 21) if x % 2 != 0}
----

== dictionary comprehension

dictionary compreshension은 dictionary 타입 객체를 생성하는 Python 문법입니다. dictionary compression은 dict 타입 생성하여 return 하므로 중괄호( { } )를 사용하고, 각 요소는 key:value 형태이어야 합니다.

아래 코드는 두 list 객체를 zip 함수를 사용하여 묶어 dict 객체를 생성합니다.

[source, python]
----
numbers = [1,2,3]
names = ["celine","jason","robert"]

student = {number:name for number, name in zip(numbers, names)}
print(student)
----

----
{1: 'celine', 2: 'jason', 3: 'robert'}
----