== Lab 4-2: 예외 처리

== 연습 1 날짜 번호 검증

이 연습에서는 Lab 4-1에서 작성한 프로그램에 기능을 추가합니다. 프로그램은 사용자가 표준 입력으로 전달한 초기 날짜 번호를 검사하여 1보다 작거나 365보다 크면 예외를 발생시킵니다. 프로그램은 except 블록에서 이 예외를 잡고 메시지를 처리합니다.

1. Visual Studio Code를 실행합니다.
2. 파일 메뉴에서 폴더 열기를 클릭하고, c:\Labs\Lab04-2\Starter 폴더를 선택합니다.
3. 작성자 신뢰 경고 창에서, 예, 작성자를 신뢰합니다 버튼을 클릭합니다.
4. Visual Studio Code 탐색기에서 Whatday.py 파일을 엽니다.
5. 제일 위쪽의 세 list 정의를 제외한 모든 코드를 try 블록으로 지정합니다.
6. day_num 변수 선언 아래에, if 절을 추가하고 day_num 변수의 값이 1보다 작거나 365 보다 크면 ValueError를 발생시키는 코드를 작성합니다. 예외는 "범위를 벗어났습니다" 메시지를 포함합니다.
7. 발생한 예외를 처리하는 except 블록을 작성합니다
8. 완성된 코드는 아래와 유사할 것입니다.
+
[source, python]
----
days_in_month  = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
days_in_leap_month  = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
month_names = ["January", "Feburary", "March", "April", "May", "June", "July", "August", "Sepetember", "October", "November", "December"]

try:
    year_num = int(input("연도를 입력하세요: "))

    if day_num < 1 or day_num > 365:
        raise ValueError("범위를 벗어났습니다")

    month_num = 0

    for days in days_in_month:
        if day_num <= days:
            break
        else:
            day_num -= days
            month_num += 1

    month_name = month_names[month_num]

    print(f"{day_num}, {month_name}")
except ValueError as e:
    print(e)

----
+
9. 작업을 저장합니다.
10. Whatday.py 프로그램을 실행합니다.
11. 프로그램이 실행되면 1보다 작거나 365보다 큰 숫자를 입력하고 발생한 예외가 안전하게 처리되는 것을 확인합니다
+
----
$ Whatday.py
1 에서 365 사이의 숫자를 입력하세요: 366
범위를 벗어났습니다
----

== 윤년 처리

**연도를 입력받는 코드 작성**

이 연습에서는 앞에서 작성한 프로그램에 윤년을 처리하는 기능을 추가합니다. 이 연습에서는 프로그램에서 사용자에게 날짜 번호 외에 연도를 묻는 메시지를 추가하며, 프로그램은 지정된 연도를 받아 해당 연도가 윤년인지 판별하는 코드를 작성합니다. 연도가 윤년이면 날짜 번호가 1에서 366까지로 지정되며, 윤년이 아니면 1에서 365로 지정됩니다. for 문을 하나 더 추가하여 윤년의 월과 쌍을 계산합니다.

1. try statment의 첫 줄 아래에, 연도를 입력하라는 문자열을 프롬프트에 출력하고 값을 읽어들여 year_num 변수에 정수 타입으로 할당하는 코드를 작성합니다.
2. 완성된 코드는 아래와 유사할 것입니다.
+
[source, python]
----
days_in_month  = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
days_in_leap_month  = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
month_names = ["January", "Feburary", "March", "April", "May", "June", "July", "August", "Sepetember", "October", "November", "December"]

try:
    year_num = int(input("연도를 입력하세요: "))
    day_num = int(input("1 에서 365 사이의 숫자를 입력하세요: "))

    ...

    print(f"{day_num}, {month_name}")
except ValueError as e:
    print(e)

----

== 윤년을 판별하는 코드 추가

1. year_num 변수 선언 코드 아래에 is_leap_year 라는 변수를 선언하는 코드를 추가하고 year_num 변수에 할당된 값이 윤년인지 아닌지를 판단하는 boolean 식으로 초기화합니다. 다음 두 항목이 모두 참인 경우 윤년에 해당합니다.
** 4로 나누어 떨어지는 경우
** 100으로 나눌 수 없고 400으로 나눌 수 있는 경우
2. isLeapYear 변수 선언 다음에 isLeapYear 값에 따라 "윤년입니다" 또는 "평년입니다"를 출력하는 if 문을 작성합니다.
3. 완성된 코드는 아래와 유사할 것입니다.
+
[source, python]
----
days_in_month  = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
days_in_leap_month  = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
month_names = ["January", "Feburary", "March", "April", "May", "June", "July", "August", "Sepetember", "October", "November", "December"]

try:
    year_num = int(input("연도를 입력하세요: "))

    is_leap_year = (year_num % 4 == 0) and ((year_num % 100 != 0) or (year_num % 400 == 0))

    if (is_leap_year):
        print("윤년입니다")
    else:
        print("평년입니다")

    day_num = int(input("1 에서 365 사이의 숫자를 입력하세요: "))

    if day_num < 1 or day_num > 365:
        raise ValueError("범위를 벗어났습니다")

    month_num = 0

    ...

    month_name = month_names[month_num]

    print(f"{day_num}, {month_name}")
except ValueError as e:
    print(e)
----
+
4. 작업을 저장합니다.
5. Whatday.py 프로그램을 실행합니다. 윤년 값이 아래 표와 같이 제대로 계산되는지 확인합니다.
+
[%header, cols="1,1" width=50%]
|===
|윤년|	평년
|1992|	2022
|2004|	1973
|1980|	1953
|===

== 윤년과 평년에 따른 1년의 일수 계산

1. is_leap_year 변수 선언 아랫 줄에, 변수 max_day_num 을 선언하고 is_leap_year 값에 따라 365(평년)와 366(윤년) 값이 할당되는 구문을 추가합니다.
2. 윤년, 평년을 출력하는 if 문을 수정하여 "1 에서 365 사이의 숫자를 입력하세요: "를 출력하는 라인을 윤년이면 "1 에서 365 사이의...", 평년이면 "1 에서 365 사이의... "를 출력하도록 수정합니다.
3. 작업을 저장하고 프로그램을 실행하여 윤년과 평년에 따라 숫자가 제대로 표시되는지 확안힙니다.
4. 아래의 예외를 발생시키는 if 문에서 dayNum 의 가장 큰 수 한계를 maxDayNum 변수로 변경합니다.
5. 완성된 코드는 아래와 유사할 것입니다.
+
[source, python]
----
days_in_month  = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
days_in_leap_month  = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
month_names = ["January", "Feburary", "March", "April", "May", "June", "July", "August", "Sepetember", "October", "November", "December"]

try:
    year_num = int(input("연도를 입력하세요: "))

    is_leap_year = (year_num % 4 == 0) and ((year_num % 100 != 0) or (year_num % 400 == 0))

    if (is_leap_year):
        max_day_num = 366
    else:
        max_day_num = 365

    day_num = int(input("1 에서 {} 사이의 숫자를 입력하세요: ".format(max_day_num)))

    if day_num < 1 or day_num > max_day_num:
        raise ValueError("범위를 벗어났습니다")

    month_num = 0

    for days in days_in_month:
        if day_num <= days:
            break
        else:
            day_num -= days
            month_num += 1

    month_name = month_names[month_num]

    print(f"{day_num}, {month_name}")
except ValueError as e:
    print(e)
----
+ 
6. 작업을 저장합니다.
7. 프로그램을 실행하고 코드가 잘 동작하는지 확인합니다.

== 윤년의 월 일을 바르게 계산

1. month_num 변수 선언 아래 줄에 if-else 문을 추가합니다. 이 if-else 문의 boolean 식에 is_leap_year 변수를 지정합니다.
2. 아래의 for 문을 if 문으로 이동합니다. if와 else 모두에 같은 for 문위 위치하도록 아래와 같이 코드를 작성합니다.
+
[source, python]
----
    if is_leap_year:
        for days in days_in_month:
            if day_num <= days:
                break
            else:
                day_num -= days
                month_num += 1
    else:
        for days in days_in_month:
            if day_num <= days:
                break
            else:
                day_num -= days
                month_num += 1
----
+
3. 작업을 저장합니다.
4. 작업을 저장하고 프로그램을 실행하여 윤년이 아직 처리되지 않는 것을 확인합니다.
5. 코드의 위쪽에서 days_in_leap_month 리스트를 확인합니다. 이 리스트는 days_in_month 리스트와 다르게 2번쨰 달이 29로 지정되어 있는 것을 확인합니다.
6. if-else문의 true 부분 for 문의 days_in_month를 days_in_leap_month 로 변경합니다.
7. 완성된 코드는 아래와 유사할 것입니다.
+
[source, python]
----
days_in_month  = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
days_in_leap_month  = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
month_names = ["January", "Feburary", "March", "April", "May", "June", "July", "August", "Sepetember", "October", "November", "December"]

try:
    year_num = int(input("연도를 입력하세요: "))

    is_leap_year = (year_num % 4 == 0) and ((year_num % 100 != 0) or (year_num % 400 == 0))

    if (is_leap_year):
        max_day_num = 366
    else:
        max_day_num = 365

    day_num = int(input("1 에서 {} 사이의 숫자를 입력하세요: ".format(max_day_num)))

    if day_num < 1 or day_num > max_day_num:
        raise ValueError("범위를 벗어났습니다")

    month_num = 0

    if is_leap_year:
        for days in days_in_leap_month:
            if day_num <= days:
                break
            else:
                day_num -= days
                month_num += 1
    else:
        for days in days_in_month:
            if day_num <= days:
                break
            else:
                day_num -= days
                month_num += 1

    month_name = month_names[month_num]

    print(f"{day_num}, {month_name}")
except ValueError as e:
    print(e)
----
+
8. 작업을 저장합니다.
9. Whatday.py 프로그램을 저장하고 프로그램을 실행하여 입력 값에 따라 아래와 같은 날짜를 출력하는 것을 확인합니다.
+
[%header, cols="1,1,1", width=70%]
|===
|연도|	날짜 번호|	날짜
|1999|	32|	February, 1
|2000|	32|	February, 1
|1999|	60|	March, 1
|2000|	60|	February, 29
|1999|	91|	April, 1
|2000|	91|	March, 31
|1999|	186|	July, 5
|2000|	186|	July, 4
|1999|	304|	October, 31
|2000|	304|	October, 30
|1999|	327|	November, 23
|2000|	327|	November, 22
|1999|	359|	December, 25
|2000|	359|	December, 24
|===