= Lab 5-1 메소드 생성과 사용

== 연습 1: 값을 반환하는 메소드에서 파라미터 사용

이 연습에서는 준비된 Utilities.py라는 모듈에 max라는 함수를 만듭니다. 이 함수는 두 개의 파라미터를 가지고, 둘 중 큰 값을 반환합니다.

모듈을 테스트하기 위해 Test.py라는 다른 모듈을 생성하고 max 함수를 호출하여 입력 받은 숫자 중 큰 수를 출력합니다. 아래 절차에 따릅니다.

**max 메소드 작성**

1. Visual Studio Code를 실행합니다.
2. 파일 메뉴에서 폴더 열기를 클릭하고 c:\Labs\Lab05-1\Starter 폴더를 엽니다.
3. 작성자 신뢰 경고 창에서, 예, 작성자를 신뢰합니다 버튼을 클릭합니다.
4. Visual Studio Code 탐색기에서 Utilities.py 파일을 엽니다. +
파일에는 아무 함수도 정의되어 있지 않습니다. 이 파일에 max 함수를 작성합니다.
5. Utilities 클래스의 To-do: Create max method here 구역에 max 라는 이름의 함수를 추가합니다.
6. 함수는 i, j 라는 이름을 가진 두 개의 파라미터를 가집니다. 함수의 바디는 두 수를 비교하여 큰 값을 return 합니다.
7. 완성된 코드는 아래와 유사할 것입니다.
+
[source, python]
----
def max(i, j):
    if i > j:
        return i
    else:
        return j
----

**max 메소드 테스트**

1. Visual Studio 파일 탐색기에서 Test.py 파일을 엽니다.
2. i, j 이름을 가진 두 변수를 선언합니다.
3. i 변수 대해 int 메소드를 사용해 표준 입력에서 입력되는 값을 int 타입으로 전달받아 할당합니다. 첫 번째 숫자를 입력하라는 메시지를 출력합니다.
4. j 변수 대해 int 메소드를 사용해 표준 입력에서 입력되는 값을 int 타입으로 전달받아 할당합니다. 두 번째 숫자를 입력하라는 메시지를 출력합니다.
5. i, j 두 변수를 파라미터 인자로 max 메소드를 호출하고 결과를 max 변수에 할당합니다.
6. max 변수를 출력하는 코드를 작성합니다.
7. 완성된 코드는 아래와 유사할 것입니다.
+
[source, python]
----
import Utilities

i = int(input("첫 번째 숫자를 입력하세요: "))
j = int(input("두 번째 숫자를 입력하세요: "))

max = max(i, j)

print(max)
----
+
8. 작업을 저장합니다.
9. 아래 명령을 실행하여 프로그램을 실행합니다.
+
----
$ python Test.py
----
+
10. 오류가 있으면 수정합니다.
11. 오류가 없으면 두 숫자를 입력하여 실행을 확인합니다.

== swap 메소드 테스트

이 연습에서는 Python의 파라미터 전달 메커니즘을 테스트하기 위해 swap 함수를 작성하고 동작을 테스트합니다. 아래 절차에 따릅니다.

1. Visual Studio Code에 열려 있는 Utilities.java 파일의 Utilities 클래스에 swap 함수를 추가합니다.
2. swap 함수를 아래와 같이 작성합니다.
a. 함수는 i, j 두 개의 파라미터를 가집니다.
b. swap 함수는 파라미터로 전달받은 두 값을 교체합니다. 임시 변수를 선언한 후 두 값 중 하나를 할당하고 임시 변수를 사용하여 값을 교환할 수 있습니다. 임시 변수의 이름은 temp이며 입니다.
3. 완성된 코드는 아래와 유사할 것입니다.
+
[source, python]
----
def swap(i, j):
    temp = i
    i = j
    j = temp
----
+
4. Test.py 모듈에서, 이전에 작성한 코드 중 import 문을 제외한 모든 코드를 삭제하거나 주석처리 합니다.
5. Test.py 모듈에서 i, j 두 변수를 선언하고 i 에는 1, j 에는 2를 할당합니다.
6. 두 변수의 값을 출력하는 코드를 작성합니다.
7. i, j 두 변수를 파라미터로 swap 메소드를 실행하는 코드를 작성합니다.
8. 두 변수의 값을 출력하는 코드를 작성합니다.
9. 완성된 코드는 아래와 유사할 것입니다.
+
[source, python]
----

----

아래 명령을 실행하여 프로그램을 컴파일 합니다.

> javac -encoding UTF-8 Utilities.java
프로그램을 실행하여 테스트하고 swap 메소드 호출후에도 i, j 변수에 저장된 값이 교환되지 않는 것을 확인합니다.

swap 메소드 호출 전: i: 1, J: 2
swap 메소드 호출 후: i: 1, J: 2