= Lab 5-2 List 사용

이 연습에서는 텍스트 파일의 이름을 main 함수의 인자로 받아 파일의 내용을 요약하는 프로그램을 작성합니다. 프로그램은 텍스트 파일의 내용을 문자열로 읽어 배열로 만들고 배열의 요소를 반복하며 처리합니다. 프로그램은 읽은 텍스트 파일의 문자 수, 모음 수, 자음 수 및 줄의 총 수를 출력합니다. 아래 절차에 따릅니다.

== 연습 1: 프로그램 실행 시 인자에서 텍스트 파일의 이름 처리

1. Visual Studio Code를 실행합니다.
2. 파일 메뉴에서 폴더 열기를 클릭하고 c:\Labs\Lab05-2\Starter 폴더를 엽니다.
3. 작성자 신뢰 경고 창에서, 예, 작성자를 신뢰합니다 버튼을 클릭합니다.
4. Visual Studio Code 탐색기에서 FileDetails.py 파일을 엽니다.
5. 명령행 인자로 받은 파라미터의 길이를 검사하는 코드를 작성합니다. 파라미터의 길이가 1보다 작거나 크면 "usage: python FileDetails FileName" 메시지를 출력하고 프로그램을 끝내는 코드를 작성합니다.
6. 프로그램 파라미터 인자가 하나일 경우 요소의 값을 String 타입 변수 fileName에 할당합니다.
7. 완성된 코드는 아래와 유사할 것입니다:
+
[source, python]
----
if len(sys.argv) != 2:
    print("usage: python FileDetails.py FileName")
    exit()
else:
    file_name = sys.argv[1]
----

== 텍스트 파일을 읽어 List에 저장

1. with 문의 주석을 해제합니다.
2. for 문을 사용하여 contents의 모든 문자를 출력하는 코드를 작성합니다. print 함수에서 줄 바꿈을 처리하지 않도록 지정합니다.
3. 완성된 코드는 아래와 유사할 것입니다.
+
[source, python]
----
import sys

if len(sys.argv) != 2:
    print("usage: python FileDetails.py FileName")
    exit()
else:
    file_name = sys.argv[1]

with open(file_name, "r") as file:
    contents = list(file.read())

for s in contents:
    print(s, end="")
----
+
4. 프로그램을 실행합니다. 오류가 있으면 수정합니다. 실행 명령은 아래와 같습니다.
+
----
$ python FileDetail.py Yesterday.txt
----
+
5. Yesterday.txt 파일의 모든 내용이 출력되는 것을 확인합니다. 
6. for 문을 삭제하거나 주석처리 합니다.

== 파일의 정보표시

1. 하나의 파라미터를 가지는 summerize 함수를 선언합니다.
2. summerize 함수에 for 문을 추가하고 파라미터로 전달 받은 객체의 요소들을 검사합니다. 
3. summerize 함수에 모음(Vowel), 자음(Consonat), 줄 바꿈(new line) 개수를 저장하기 위한 변수를 선언하고 0으로 초기화합니다.
4. summerize 함수에서 argument로 전달받은 contents에서 모음, 자음, 라인수를 세는 코드를 작성하고 각 변수에 할당는 코드를 작성합니다.
5. summerize 함수에서 아래와 같은 메시지를 출력하는 코드를 작성합니다.
** 파일에 포함된 문자 개수
** 파일에 포함된 모음 수
** 파일에 포함된 자음 수
** 파일의 줄 수
6. 파일의 끝에서, contents 리스트를 argument로 summerize 함수를 호출하는 코드를 작성합니다.
7. 완성된 코드는 아래와 유사할 것입니다.
+
[source, python]
----
import sys

def summerize(contents):
    vowels, consonats, lines = 0, 0, 0
    for s in contents:
        if s.isalpha():
            if s in "AEIOUaeiou":
                vowels += 1
            else:
                consonats += 1
        elif s == "\n":
            lines += 1
    print("총 문자 수:", len(contents))
    print("모음 수:", vowels)
    print("자음 수:", consonats)
    print("라인 수:", lines)


if len(sys.argv) != 2:
    print("usage: python FileDetails.py FileName")
    exit()
else:
    file_name = sys.argv[1]

with open(file_name, "r") as file:
    contents = list(file.read())

summerize(contents)
----

8. 작업을 저장합니다.
9. 프로그램을 실행합니다. 오류가 있으면 수정합니다.