= Numeric 타입

* 숫자로 표현 될 수 있는 타입
* Arithmetric Operation(산술 연산)이 가능한 데이터를 표현
* 데이터의 크기에 따라 크기가 가변적
* int(정수), Float(실수), Complex(복소수)

---

Python에서 Numeric 타입은 산술 연산이 가능한 데이터 타입을 의미합니다. Python에서 Numeric 타입은 Java, C#, C, C++등의 언어와 달리 크기가 정해져 있지 않고, 데이터의 크기에 따라 가변적으로 변화합니다.

Python은 산술 연산이 가능한 데이터를 Numeric으로 정의하고 데이터의 표현 방법에 따라 3가지 타입을 제공합니다.

* int(정수): 0을 포함하며, 양수 및 음수
* float(실수): 소수점을 포함하는 실수
* complex(복소수): 실수와 허수의 합으로 이루어진 복소수

== int(정수)

int는 0을 포함하는 양의 정수와 음의 정수를 표현할 수 있는 데이터 타입이며, int 타입의 객체입니다. Python 도움말(help 함수)에서 설명하는 int 타입의 개요는 아래와 같습니다.

----
Help on class int in module builtins:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
----

아래 코드와 같이 정수를 변수에 할당하면 int 타입으로 타입이 지정됩니다.

[source, python]
----
a = 5
b = -5
print(type(a), type(b))
----
----
<class 'int'> <class 'int'>
----

정수는 2진수, 8진수, 16진수로 표현될 수 있습니다. 정수 앞에 0b(binary), 0o(octomal), 0x(hexdecimal)을 붙이면 각 진법의 숫자는 10진법의 숫자로 표시됩니다.

[source, python]
----
a = 0b1010
b = 0o12
c = 0xA
print(a, b, c)
----
----
10 10 10
----

bin, oct, hex 함수를 사용하여 정수를 2진수, 8진수, 16진수로 변환할 수 있습니다. 세 함수는 2진수, 8진수, 16진수로 변환된 숫자가 아닌 문자열 형태로 반환합니다.

[source, python]
----
a = bin(10)
b = oct(10)
c = hex(10)

print(a, b, c)
----

----
10 10 10
----

== float(실수)

Python의 float은 부동 소수점을 표현합니다. 32비트 부동 소수점(단정도 부동소수점)인 float와 64비트 부동 소수점(배정도 부동소수점)으로 실수를 위한 두 가지 타입을 제공하는 Java나 C#등의 언어와 달리 Python의 float은 모든 크기의 실수를 표현합니다. Python 도움말(help 함수)에서 설명하는 int 타입의 개요는 아래와 같습니다.

----
class float(object)
 |  float(x=0, /)
 |
 |  Convert a string or number to a floating point number, if possible.
----

지수(exponent) 표기법을 사용하여 표시할 수도 있습니다.

[source, python]
----
>>> 0.23193202032E8
23193202.032
>>> 1412232.22E-10
0.000141223222
>>>
----

위 코드에서 E는 지수(Exponent)라는 의미이며, 대문자가 아니더라도 소문자 역시 똑같은 의미로 사용됩니다. 위의 예제에서 0.23193202032E8는 0.23193202032 * 10^8이라고 보시면 됩니다. 즉, 0.23193202032 곱하기 10의 8승은 23193202.032라는 값을 지니고, 1412232.22E-10에서는 10^-10이니 이것은 1412232.22 곱하기 10의 마이너스 10승을 의미하며, 0.000141223222라는 값을 가집니다.

아래 코드의 경우,

[source, python]
----
>>> 5.4 + 1.2
6.6000000000000005
>>> 1.4 - 1.1
0.2999999999999998
----

결과는 예상하는 것과 같이 6.6, 0.3 등으로 보이지 않습니다.  이는 진법 변환에 따른 오차에 의한 것으로 10진수를 2진수로 변환시킬때 10진수의 유한 소수가 2진수에선 무한 소수가 되는 경우가 있습니다. 10진수 0.125를 2진수로 고치면 

----
0.125 * 2 = 0.25 (0)
0.25 * 2 = 0.5 (0)
0.5 * 2 = 1.0 (1)
0.0 (계산 마침)
----

위와 같이 계산되어 최종적으로 2진수 0.001이 됩니다. 이와 같은 방법으로 10진수 0.1를 2진수로 변환한다고 하면 아래와 같은 절차로 계산됩니다.

----
0.1 * 2 = 0.2 (0)
0.2 * 2 = 0.4 (0)
0.4 * 2 = 0.8 (0)
0.8 * 2 = 1.6 (1)
...
----

소수부가 0이 나올때까지 2를 곱하게 되는데, 여기서 뒷자리는 2,4,8,6의 반복으로 계속 끝이 없는 무한 소수가 됩니다. 이는 사실 파이썬 자체만의 문제가 아니라 컴퓨터에서 부동소수점을 표현하는 가장 널리 쓰이는 표준인 IEEE 754를 따르는 프로그래밍 언어들이 이러한 문제를 가지고 있습니다. 정밀한 계산을 해야 한다면 파이썬의 decimal 모듈을 사용할 수 있습니다.

== Complex(복소수)

복소수는 실수부와 허수부로 나뉘어 _a + bi_ 꼴로 나타낼 수 있는 모든 수를 의미합니다. Python에서는 복소수를 표현하기 위해 complex 타입을 지원합니다. Python 도움말(help 함수)에서 설명하는 int 타입의 개요는 아래와 같습니다. Python에서는 허수 단위로 i가 아닌 j를 사용합니다. Python 도움말(help 함수)에서 설명하는 complex 타입의 개요는 아래와 같습니다.

----
class complex(object)
 |  complex(real=0, imag=0)
 |
 |  Create a complex number from a real part and an optional imaginary part.
 |
 |  This is equivalent to (real + imag*1j) where imag defaults to 0.
----

아래 코드와 같이 x 변수에 '7 - 3j'을 할당하면 x는 복소수인 complex 타입으로 선언됩니다.

[source, python]
----
>>> x = 7 - 3j
>>> type(x)
<class 'complex'>
----

image와 real 속성을 사용하여 허수부와 실수부를 확인할 수 있습니다. conjugate 함수는 켤레 복소수(conjugate complex number)를 return 합니다.

[source, python]
----
>>> x.imag 
-3.0 
>>> x.real 
7.0 
>>> x.conjugate() 
(7+3j) 
----

아래 코드와 같이 complex 함수로 실수부와 허수부를 넘겨줌으로써 복소수를 만들 수도 있습니다. 

[source, python]
----
>>> y = complex(2.5, 4)     # y = 2.5 + 4j 
>>> x + y 
(9.5+1j) 
>>> x - y 
(4.5-7j) 
>>> x / y 
(0.24719101123595505-1.595505617977528j) 
>>> x * y 
(29.5+20.5j) 
----

complex 함수로 실수부만 넘길 수 있고, 복소수의 형태를 갖춘 문자열을 넘겨도 복소수를 만들 수 있습니다.

[source, python]
----
>>> complex(1.1, 3.4) + 2j * 7.6j 
(-14.1+3.4j) 
>>> complex(3) 
(3+0j) 
>>> complex("7-2j") 
(7-2j) 
----

절대값을 구하는 abs() 함수를 통해서 복소수 3+4j의 절댓값을 얻을 수 있습니다. 복소수 3+4j의 절댓값은 sqrt(3^2 + 4^2)입니다.
[source, python]
----
>>> z = 3 + 4j 
>>> abs(z) 
5.0 
----