= Sequence 타입

* 메모리에 연속적으로 저장되는 요소들을 가지는 데이터 타입
* 문자열(str), 리스트(list), 투플(tuple)
* sequence 타입은 slice, range, in 등의 공통 기능을 가짐.

---

메모리에 연속적으로 저장되는 요소들을 가지는 데이터 타입으로, 문자열, 리스트, range, 투플등과 같이 값이 연속적으로 이어진 자료형입니다. 이 자료형들은 range, in 등의 공통 기능을 가집니다.

Python은 세 가지의 sequence 타입을 제공합니다.

* 문자열(str 타입): 문자(charcter)들의 sequence 입니다.
* 리스트(list 타입): 요소(element)들의 sequence 입니다.
* 투플(tuple 타입): 리스트와 같으나, 생성시 선언된 요소를 변경할 수 없습니다.

== Sequence 타입의 공통 기능

=== 일반적인 동작

모든 Sequence 타입은 순서가 유지되고, 정수로 인덱싱하며, 길이가 있습니다. 길이는 len() 함수를 사용하여 구할 수 있습니다.

[source, python]
----
a = "Hello"     # Sequence 타입인 문자열, 순서가 유지됨
a[1]            # 0으로 시작하는 정수로 인덱싱, "e" 문자 출력
a[-1]           # 인덱스가 -가 되면 시퀀스의 끝요소부터 인덱싱합. "o" 문자 출력
len(a)          # len() 함수를 사용하여 길이를 알 수 있음. 길이는 5
----

----
e
o
5
----

* 연산자를 사용하여 복제할 수 있습니다.

[source, python]
----
a = "hello"
print(a * 3)    # a 문자열을 3번 복제. "hellohellohello"를 출력
----

----
hellohellohello
----

* 같은 타입의 Sequence는 + 연산자를 사용하여 이어 붙일 수 있습니다.

[source, python]
----
a = "hello "
b = "celine"
print(a + b)    # a와 b를 이어 붙임 "hello celine"을 출력
----

----
hello celine
----

== 인덱싱

인덱스를 사용하여 특정 위치의 요소를 얻을 수 있습니다. 인덱싱 기호는 C, C#, Java 등의 언어에서와 마찬가지로 대괄호 기호([ ])를 사용합니다.

[source, python]
----
a = "123456789"
print(a[0])
----

----
1
----

인덱스가 Sequence의 범위를 벗어나면 Java 등의 언어에서와 마찬가지로 Error가 발생합니다.

[source, python]
----
a = "123456789"
print(a[9])
----

----
Traceback (most recent call last):
  File "D:\Code\Python\Test.py", line 2, in <module>
    print(a[9])
          ~^^^
IndexError: string index out of range
----

=== 슬라이싱

* 슬라이싱을 사용하여 Sequence의 일부를 얻을 수 있습니다. s[start:end] 또는 s[start:end:step] 형식을 사용합니다. end 인덱스에 해당하는 요소는 출력하지 않습니다.

[source, python]
----
a = "123456789"
print(a[1:5])       # 1번 인덱스 요소에서 4번 인덱스 요소까지를 얻음, "2345" 
print(a[0:10:2])    # 0번 인덱스 요소에서 9번 인덱스 요소까지에서 2씩 건너뛰며 읽은 요소들을 얻음 "13579"
----

----
2345
13579
----

* 산술 연산 가능 요소를 포함하는 Sequence 타입은 sum(), min(), max() 등의 집계 함수를 사용할 수 있습니다. 문자열에서도 min(), max() 집계 함수를 사용할 수 있습니다.

[source, python]
----
a = "abcde"
print(min(a))
print(max(a))

l = [1,2,3,4,5,6,7,8,9]
print(sum(l))
print(min(l))
print(max(l))
----

=== 이터레이션

for 루프를 사용하여 모든 원소에 대한 이터레이션을 수행할 수 있습니다.

[source, python]
----
a = "abcde"
for s in a:
    print(s)
----

== Sequence 타입 객체 메소드

Sequence 타입의 객체(문자열, 리슽, 투플)은 아래 메소드들을 가지고 있습니다.

**count() 메소드**

count() 메소드는 객내에의 요소 중 파라미터로 전달받은 값에 해당하는 값의 개수를 반환합니다.

[source, python]
----
tuple = ('1','2','3','4','5','6','7','8','9')
print(tuple.count('2'))
----

----
1
----

**index() 메소드**

count() 메소드는 객내에의 요소 중 파라미터로 전달받은 값에 해당하는 값의 인덱스 값을 정수로 반환합니다.

[source, python]
----
list = ['1','2','3','4','5','6','7','8','9']
print(list.index("2"))
----

----
1
----

**join() 메소드**

문자열을 파라미터로 전달받은 Sequence 값의 각 요소 사이에 삽입한 값을 문자열로 반환합니다.

[source, python]
----
string = "123456789"
list = ['1','2','3','4','5','6','7','8','9']

print(".".join(string))
print(".".join(list))
----

----
'1.2.3.4.5.6.7.8.9'
'1.2.3.4.5.6.7.8.9'
----

