= 문자열 타입

* 연속된 문자열의 나열
* 큰 따옴표(" ") 또는 작은 따옴표(' ')로 표현
* str 타입 객체이며, 불변형(Immutable)

---

Python에서 문자열은 Sequence 타입으로, 큰 따옴표(" ") 또는 작은 따옴표(' ')로 둘러싸인 문자(Chractor)들의 순서를 의미하며, str 타입의 객체입니다. Python 도움말(help 함수)에서 설명하는 bool 타입의 개요는 아래와 같습니다.

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.

== 문자열 생성

Python에서는 4가지 방법을 사용하여 문자열을 정의할 수 있습니다. 크게는 큰 따옴표와 작은 따옴표 모두를 사용할 수 있으며, 어떤 방법을 사용하든 결과는 동일합니다. PEP에서는 두 방법 중 하나를 사용하는 것을 특별히 권장하지 않으며, 자유롭게 사용하는 것을 추천합니다.

**큰따옴표로 사용**

큰 따옴표를 사용하여 문자열을 정의할 수 있습니다. 전형적인 방법으로, "Hello World"와 같이 사용합니다.

[source, python]
----
message = "Hello, World!"
----

문자열이 `'` 문자를 포함해야 하는 경우, Escape character를 사용할 수도 있지만, 큰 따움표로 문자열을 선언할 경우 `'` 문자를 그대로 사용할 수 있습니다. 

[source, python]
----
print("hello, ' World!")
----

----
hello, ' World!
----

**작은 따옴표 사용**

큰 따옴표를 사용하여 문자열을 정의할 수 있습니다. 전형적인 방법으로, 'Hello World'와 같이 사용합니다.

[source, python]
----
message = "Hello, World!"
----

문자열이 `"` 문자를 포함해야 하는 경우, Escape character를 사용할 수도 있지만, 큰 따움표로 문자열을 선언할 경우 `"` 문자를 그대로 사용할 수 있습니다. PEP에서는 문자열이 `'` 를 포함하는 경우 문자열 선언에 큰 따옴표를, `"` 를 포함하는 경우 작은 다옴표를 사용하는 것을 권장합니다.

[source, python]
----
print('hello, " World!')
----

----
hello, " World!
----

문자열이 `'` 를 포함하는데 문자열 선언에 작은 따옴표를 사용하면 에러가 발생합니다.

----
>>> print('hello, ' World!')
  File "<stdin>", line 1
    print('hello, ' World!')
          ^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
----

**여려줄인 문자열을 단일 변수에 할당**

아래와 같이 여러 줄인 문자열을 변수에 할당해야 할 경우가 있을 경우, 일반적으로 Escape character를 사용합니다.

[source, python]
----
s = "강나루 건너서\n밀밭 길을"
print(s)
----

----
강나루 건너서
밀밭 길을
----

이 벙법은 여러 줄로 구성된 문자열을 변수에 할당하기 위해 일반적으로 사용하는 방법이지만, 불편할 수 있습니다. 이런 경우 큰 따옴표 3개 또는 작은 따옴표 2개를 사용하여 문자열을 정의할 수 있습니다.

[source, python]
----
message = """강나루 건너서
밀밭 길을
구름에 달 가듯이
가는 나그네"""
----

----
강나루 건너서
밀밭 길을
구름에 달 가듯이
가는 나그네
----

큰 따옴표 대신 작은 따옴표를 사용할 수도 있습니다.

[source, python]
----
message = """길은 외줄기
남도 삼백리

술 익는 저녁마다
타는 저녁 놀"""

print(message)
----

----
길은 외줄기
남도 삼백리

술 익는 저녁마다
타는 저녁 놀
----

== Escape Character

Escape Character는 프로그래밍 할 때 사용할 수 있도록 미리 정의해 둔 문자 조합을 말합니다. Python에서 사용할 수 있는, 자주 사용되는 Escape Character는 다음과 같습니다.

[cols="1, 3"]
|===
|문자|설명
|\n |문자열 안에서 줄을 바꿀 때 사용
|\t |문자열 사이에 탭 간격을 줄 때 사용
|\\ |\를 그대로 표현할 때 사용
|\'|작은따옴표(')를 그대로 표현할 때 사용
|\"|큰따옴표(")를 그대로 표현할 때 사용
|\r|캐리지 리턴(줄 바꿈 문자, 커서를 현재 줄의 가장 앞으로 이동)
|\f|폼 피드(줄 바꿈 문자, 커서를 현재 줄의 다음 줄로 이동)
|\a|벨 소리(출력할 때 PC 스피커에서 '삑' 소리가 난다)
|\b|백 스페이스
|\000|널 문자
|===

== 문자열 포매팅

문자열은 몇 가지 방법으로 포매팅 할 수 있습니다.

**포맷 코드 사용**

문자열 포맷 코드를 사용하여 문자열을 표현할 수 있습니다. 문자열에 삽입될 자리에 문자열 포맷 코드를 사용하고, 삽입될 문자열은 %로 연결합니다.

[source, python]
----
message = "Hello, %s" % "celine"
print(message)
----

----
Hello, celine
----

문자열 포맷 코드는 문자열, 문자, 정수, 실수등 형태에 따라 다르게 표현합니다.

[cols="1, 3", option="header"]
|===
|포맷코드|설명
|%s	|문자열(String)
|%c |문자 1개(character)
|%d	|정수(Integer)
|%f	|부동소수(floating-point)
|%o	|8진수
|%x	|16진수
|%%	|Literal % (문자 % 자체)
|===

한 문자열에 하나 이상의 포맷 코드를 사용할 수 있습니다. 이 경우 삽입되는 문자열을 표시하는 % 기호뒤의 데이터를 표시하기 위해 괄호( ( ) )를 사용해야 합니다.

[source, python]
----
message = "%s is %d years old" % ("celine", 21)
print(message)
----

----
celine is 21 years old
----

**format() 함수 사용**

format() 함수를 사용하면 좀 더 유연한 형식의 포맷을 사용할 수 있습니다. 

[source, python]
----
message = "{} is {} years old".format("celine", 21)
print(message)
----

----
celine is 21 years old
----

format() 함수에 변수의 이름을 지정하여 사용할 수 있습니다.

[source, python]
----
message = "{} is {age} years old".format("celine", age=21)
print(message)
----

----
celine is 21 years old
----

**f문자열 포매팅**

Python 3.6 버전부터 f 문자열 포매팅 기능을 사용할 수 있습니다. 문자 선언시 문자열 앞에 f 를 붙이면 f 문자열 포매팅 기능을 사용할 수 있습니다.

[source, python]
----
name = "celine"
age = 21
message = f"{name} is {age} years old"
print(message)
----

----
celine is 21 years old
----

f 문자열 포매팅에서는 expression을 사용할 수 있습니다.

[source, python]
----
name = "celine"
age = 21
message = f"{name} is {age + 1} years old"
print(message)
----

== 문자열 메소드

**upper(), lower() 메소드**

upper() 메소드와 lower() 메소드는 문자열의 문자를 대문자 또는 소문자로 바꿉니다.

[source, python]
----
title = "sweet child o' mine"
title.upper()
title.lower()
----

----
SWEET CHILD O' MINE
sweet child o' mine
----

**lstrip(), rstrip(), strip() 메소드**

lstrip(), rstrip(), strip() 메소드는 문자열외 왼쪽, 오른쪽, 양쪽의 공백 문자열을 지웁니다.

[source, python]
----
title = "   celine    "
message = " hi"
print(title.lstrip() + message)
print(title.rstrip() + message)
print(title.strip() + message)
----

**split() 메소드**

split() 메소드는 메소드의 파라미터로 전달받은 값을 구분자로 사용하여 분리된 문자열 목록을 리스트로 return 합니다. 파라미터가 없을 경우 공백문자(whitespace)를 구분자로 사용합니다.

[source, python]
----
sentence = "얇은 사 하이얀 고깔은 고이 접어서 나빌레라"
words = sentence.split()
print(words)

row = "20090101,celine,CE"
data = row.split(",")
print(data)
----

----
['얇은', '사', '하이얀', '고깔은', '고이', '접어서', '나빌레라']
['20090101', 'celine', 'CE']
----