= Packing, Unpacking

* 변수에 할당되는 값의 개수를 유연하게 지정할 수 있는 방법
* 하나의 변수에 여러개의 값이 할당되고, list 또는 dictionary 타입으로 선언됨
** 변수명 앞에 *을 붙여 list 타입으로 선언
** 변수명 앞에 **을 붙여 dictionary 타입으로 선언

---

하나의 변수에 값이 여러개 할당되는 것이 유리한 경우가 있습니다. 특히 함수의 파라미터로 사용될 때 입력되는 argument의 개수를 알 수 없는 경우 유용하게 사용될 수 있습니다.

Python은 하나의 변수에 여러개의 값이 할당되는 것을 허용합니다. 이를 packing이라고 하며, 반대를 unpacking이라고 합니다.

== Packing

a, b라는 변수가 있고, a에는 1을, b에는 2,3,4를 할당해야 할 경우 아래와 같이 b 변수에 asterisk(\*)를 사용하여 선언하여 사용할 수 있습니다. `*` 를 사용하여 변수에 값을 할당하는 것을 starred assignment라고 부릅니다.

[source, python]
----
a, *b = 1, 2, 3
print(b)
----

----
1 [2, 3]
----

이런 경우 b는 list 타입으로 선언됩니다. 이와 같이 여러 변수를 하나의 변수에 할당하는 것을 packing이라고 하고, 하나의 asterisk(*)를 사용하여 변수를 선언하면 변수는 list 타입이 됩니다.

== Unpacking 

Packing 되어 선언된 변수를 `*`를 사용하여 함수의 argument로 넘기면 list의 모든 요소의 값을 풀어줍니다. 아래 코드는 a 변수를 [1,2,3]인 list 형태가 아닌 1, 2, 3 각각의 int 객체로 출력합니다.

[source, python]
----
*a, b, c = 1, 2, 3, 4, 5
print(*a, b, c)
----

----
1 2 3 4 5
----

== 주의 사항

starred assignment 변수는 단독으로 선언될 수 없습니다. 아래와 같이 선언하면 에러가 발생합니다.

[source, python]
----
*a = 1, 2, 3
----

----
 Cell In[57],   line 1
    *a = 1, 2, 3
    ^
SyntaxError: starred assignment target must be in a list or tuple
----

starred assignment 변수가 앞에 선언되면 뒤에 선언된 파라미터의 개수를 제외한 변수가 packing 되어 저장됩니다.

[source, python]
----
*a, b, c = 1, 2, 3, 4, 5
print(a, b, c)
----

----
[1, 2, 3] 4 5
----