= list 타입

* 다양한 타입의 요소들의 나열
* 대괄호( [ ] )를 사용하여 선언하며, 쉼표( , )로 구분
* list 타입 객체이며, 가변형(Mutable)

---

Python에서 리스트는 Sequence 타입으로, 대괄호( [ ] ) 둘러싸였으며 쉼표( ,) 로 구분된 다양한 타입의 요소들의 나열이며. list 타입의 객체입니다. Python 도움말(help 함수)에서 설명하는 bool 타입의 개요는 아래와 같습니다.

----
class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
----

== list 생성

list는 대괄호( [ ] )를 사용하여 생성하며, 각 요소는 쉼표( , )로 구분됩니다. 아래 코드는 요소를 포함하지 않는 list를 선언합니다.

[source, python]
----
list = []
----

여러개의 숫자를 요소로 갖도록 선언합니다.

[source, python]
----
list = [1,2,3,4,5]
----

여러 문자열을 요소로 갖도록 선언합니다.

[source, python]
----
list = ["celine","robert","albert"]
----

다양한 요소를 포함할 수 있습니다.

[source, python]
----
list = [1 3.14, "celine"]
----

list는 list를 포함할 수 있습니다.

[source, python]
----
list = [1, 3.14, ["celine", "james"]]
----

== list 슬라이싱

list는 문자열과 같이 Sequence 타입이므로, 인덱싱과 슬라이싱을 사용할 수 있습니다. 다른 점은, list는 가변형(Mutable) 타입이므로 요소를 변경하거나 수정, 삭제, 삽입할 수 있습니다.

* 슬라이싱을 사용하여 list의 요소를 수정할 수 있습니다.

[source, python]
----
l = [1,2,3,4,5,6,7,8,9]
l[2:4] = ['a', 'b']
print(l)
----

----
[1, 2, 'a', 'b', 5, 6, 7, 8, 9]
----

* 슬라이싱의 사용하여 list내의 요소를 삭제할 수 있습니다.

[source, python]
----
l = [1,2,3,4,5,6,7,8,9]
del l[2:4]
print(l)
----

== list 값 수정

list는 문자열, tuple과 달리 가변형 타입이므로 요소의 값을 수정하거나 요소를 삭제, 수정할 수 있습니다.

**요소 추가**

두 가지 방법으로 list에 요소를 추가할 수 있습니다. append() 메소드를 사용하면 해당 list 객체의 제일 마지막에 요소를 추가합니다.

[source, python]
----
list = [1,2,3]
list.append(0)
print(list)
----

----
[1, 2, 3, 0]
----

insert 메소드를 사용하면 요소가 삽입될 위치를 지정할 수 있습니다. insert 메소드는 두 파라미터를 필요로 하며, 첫 번째 파라미터는 삽입될 요소의 인덱스, 두 번째 파라미터는 삽입될 요소입니다.

[source, python]
----
list = [1,2,3]
list.insert(1, 1.5)
print(list)
----

----
[1, 1.5, 2, 3]
----

**요소 삭제**

두 가지 방법으로 list의 요소를 삭제할 수 있습니다. del 명령을 사용하여 요소를 삭제할 수 있습니다. del은 메모리에서 값을 제거하는 역할을 하는 Python에서 제공하면 명령이며, 이 명령을 사용하여 list내의 값을 인덱스를 사용하여 삭제할 수 있습니다.

[source, python]
----
list = [1,2,3]
del list[1]
print(list)
----

----
[1, 3]
----

값을 이용하여 list의 요소를 삭제하라면 list 객체의 remove() 메소드를 사용할 수 있습니다. 

[source, python]
----
list = [1,2,3]
list.remove(2)
print(list)
----

----
[1, 3]
----

== list 메소드

**sort() 메소드**

list의 요소를 정렬합니다. 기본 값은 오름차순 정렬입니다.

[source, python]
----
list = [4,2,1,3,4]
list.sort()
print(list)
----

----
[1, 2, 3, 4, 4]
----

내림차순 정렬은 reverse 파라미터에 True 값을 할당하여 실행할 수 있습니다.

[source, python]
----
list = [4,2,1,3,4]
list.sort(reverse=True)
print(list)
----

----
[4, 4, 3, 2, 1]
----

**reverse() 메소드**

list 객체의 요소를 역순으로 정렬합니다. 

[source, python]
----
list = [1,2,3,4,5]
list.reverse()
print(list)
----

----
[5, 4, 3, 2, 1]
----

**pop() 메소드**

리스트의 제일 마지막 요소를 return 하고 그 값을 삭제합니다. 이 메소드를 사용하여 list를 stack과 같이 사용할 수 있습니다.

[source, python]
----
list = [1,2,3,4,5]
element = list.pop()
print(element)
print(list)
----

----
[1, 2, 3, 4]
----

pop 메소드에 정수를 파라미트로 전달하면 해당 정수의 인덱스에 해당하는 요소를 반환하고 삭제합니다.

[source, python]
----
list = [1,2,3,4,5]
element = list.pop(2)
print(element)
print(list)
----

----
[1, 2, 4, 5]
----

**extend() 메소드**

extends 메소드 파라미터로 전달된 list를 추가합니다. += 연산과 동일합니다.

[source, python]
----
list = [1,2,3,4,5]
element = list.extend(["celine"])
print(list)
----

----
[1, 2, 3, 4, 5, 'celine']
----