= tuple 타입

* 다양한 타입의 요소들의 나열
* 괄호( () )를 사용하여 선언하며, 쉼표( , )로 구분
* tuple 타입 객체이며, 불변형(Immutable)

---

Python에서 tuple은 Sequence 타입으로, 괄호( ( ) ) 로 표시되는 쉼표( , ) 로 구분된 다양한 타입의 요소들의 나열이며, tuple 타입의 객체입니다. list객체와 유사하게 동작하지만, 선언 후 값을 변경할 수 없는 불변형(Immutable) 타입입니다. Python 도움말(help 함수)에서 설명하는 tuple 타입의 개요는 아래와 같습니다.

----
class tuple(object)
 |  tuple(iterable=(), /)
 |
 |  Built-in immutable sequence.
 |
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |
 |  If the argument is a tuple, the return value is the same object.
----

== tuple 생성

tuple은 괄호( ( ) )를 사용하여 생성되며, 각 요소는 쉼표( , )로 구분됩니다. 아래 코드는 요소를 포함하지 않는 tuple을 선언합니다.

[source, python]
----
tuple = ()
----

여러개의 숫자를 요소로 갖도록 선언합니다.

[source, python]
----
tuple = [1,2,3,4,5]
----

여러 문자열을 요소로 갖도록 선언합니다.

[source, python]
----
tuple = ("celine", "robert", "albert")
----

다양한 요소를 포함할 수 있습니다.

[source, python]
----
tuple = (1, 3.14, "celine")
----

tuple은 list, tuple을 포함할 수 있습니다.

[source, python]
----
tuple = (1, 3.14, ["celine", "james"])
tuple = (1, 3.14, ("celine", "james"))
----

== tuple과 list의 차이

tuple과 list는 비슷하지만, tuple은 불변형(Immutable)이고 list는 가변형(Mutable)이라는데 큰 차이가 있습니다. list는 포함된 요소의 값을 변경할 수 있고, 요소의 삽입, 삭제가 가능합니다.

[source, python]
----
list = [1,2,3,4,5]
list[2] = 10
print(list)

tuple = (1,2,3,4,5)
tuple[2] = 10
print(tuple)
----

----
[1, 2, 10, 4, 5]
Traceback (most recent call last):
  File "D:\My Document\GoogleDrive\100 강의자료\Python\Programming with Python\Module 02 Python Programming Language\Code\Test.py", line 6, in <module>
    tuple[2] = 10
    ~~~~~^^^
TypeError: 'tuple' object does not support item assignment
----

**공통점**

1. 여러 종류의 여러 데이터를 담을 수 있는 컨테이너 타입
+
tuple과 list 모두 다양한 타입의 여러 데이터를 담을 수 있습니다.
+
[source, python]
----
list = [1,2,3,4,5,6,7,8,9]
tuple = (1,2,3,4,5,6,7,8,9)
----
+
2. Unpacking
+
타입의 요소들을 여러 변수에 각각 할당할 수 있습니다.
+
[source, python]
----
list = [1,2,3,4,5]
tuple = (1,2,3,4,5)

a, b, c, d, e = list
a, b, c, d, e = tuple
----
+
3. 인덱스를 통해 요소에 접근
+
인덱스를 통해 각 요소에 접근할 수 있습니다.
+
[source, python]
----
list = [1,2,3,4,5]
tuple = (1,2,3,4,5)

i = list[2]
j = tuple[2]
----
+
4. 슬라이싱을 통해 요소에 접근
+
슬라이싱을 통해 요소에 접근할 수 있습니다.
+
[source, python]
----
list1 = [1,2,3,4,5,6,7,8,9]
list2 = list1[0:9:2]
print(list2)

tuple1 = (1,2,3,4,5,6,7,8,9)
tuple2 = tuple1[0:9:2]
print(list2)
----
+
----
[1, 3, 5, 7, 9]
(1, 3, 5, 7, 9)
----
+
5. 요소는 열거될 수 있음
+
요소들은 열거될 수 있습니다. 예를 들면 for 문을 사용하여 모든 요소에 접근할 수 있습니다.
+
[source, python]
----
list = [1,2,3,4,5]
tuple = (1,2,3,4,5)

for i in list:
    print(i)

for i in tuple:
    print(i)
----

**차이점**

1. list는 dictionary의 key 값으로 쓰일 수 없으나, tuple은 사용할 수 있다.
+
key, value 쌍으로 구성되는 dictionary 타입의 key에는 불변형 타입만 사용될 수 있습니다. 
+
[source, python]
----
list = [1,2,3,4,5]
tuple = (1,2,3,4,5)

dict1 = {tuple, "Dictionary"}
print(dict1)
dict2 = {list, "Dictionary"}
print(dict2)
----
+
2. 모든 값을 복사할 경우 list 요소는 새 객체로 생성되지만, tuple은 동일한 객체를 참조한다.
+
모든 요소를 복사할 경우, list 요소는 새 객체로 생성되지만, tuple은 같은 객체를 참조하는 형식으로 할당됩니다. 즉, tuple의 경우 할당된 변수가 원본과 같은 객체를 가리킵니다.
+
[source, python]
----
list1 = [1,2,3,4,5,6,7,8,9]
list2 = list1[:]
print(list1 is list2)

tuple1 = (1,2,3,4,5,6,7,8,9)
tuple2 = tuple1[:]
print(tuple1 is tuple2)
----
+
list의 경우 Java, C#등의 언어에서 Reference 참조와 같이 동작하여 side effect가 발생하지만, tuple의 경우 발생하지 않습니다. 이는 Python의 메모리 절약의 한 전략입니다.

**용도**

Tuple은 일반적으로 2개에서 5개 사이의 요소들을 저장할 때 사용되며, 하나 이상의 데이터를 즉석에서 만들어 이용하고 싶을때 주로 사용합니다. 일반적으로 같은 요소를 가지고 있을 때 list 타입 객체보다 tuple 타입 객체가 차지하는 공간이 적습니다.

== Packing





https://wikidocs.net/15