= Set 타입

* 수학에서 말하는 집합(set)
* 순서가 중요하지 않으며, 중복된 자료를 허용하지 않음

---

Python에서 set은 수학에서 사용하는 집합(set)에 해당하는 객체이며, set 함수를 호출하여 생성되는 set 타입의 객체입니다. Python 도움말(help 함수)에서 설명하는 set 타입의 개요는 아래와 같습니다.

----
class set(object)
 |  set() -> new empty set object
 |  set(iterable) -> new set object
 |
 |  Build an unordered collection of unique elements.
----

== set 생성

set은 set 함수를 사용하여, 파라미터로 Sequence 객체를 사용하여 생성합니다. 아래 코드는 원소를 포함하지 않는 set을 선언합니다.

[source, python]
----
set = set()
----

문자열, list, tuple 등 Sequence 객체를 인자로 set을 생성할 수 있습니다. set은 순서를 고려하지 않는 자료구조로, 입력된 순서와 관계없이 표시되며, 인덱스로 값을 얻을 수 없습니다.

[source, python]
----
s = set([1,2,3,9,4])
names = (set(["celine", "james", "robert"]))
print(s)
print(names)
----

----
{1, 2, 3, 4, 9}
{'robert', 'james', 'celine'}
----

set은 중복된 값을 허용하지 않습니다. 두 번째로 입력된 같은 값의 요소는 무시됩니다.

[source, python]
----
names = (set(["celine", "james", "robert","james"]))
print(names)
----

----
{'james', 'celine', 'robert'}
----

문자열에서도 같은 문자는 무시됩니다.

[source, python]
----
s = set("hello")
print(s)
----

----
{'e', 'h', 'l', 'o'}
----

== 집합 연산

set 타입 객체들간에는 교집합, 차집합, 합집합을 구할 수 있습니다.

**합집합**

`|` 연산자를 사용해서 두 집합간의 합집합을 구할 수 있습니다.

[source, python]
----
s1 = set([1, 2, 3, 4, 5, 6])
s2 = set([4, 5, 6, 7, 8, 9])
print(s1 | s2)
----

----
{1, 2, 3, 4, 5, 6, 7, 8, 9}
----

union() 메소드를 사용해서 동일한 값을 구할 수 있습니다.

[source, python]
----
s1 = set([1, 2, 3, 4, 5, 6])
s2 = set([4, 5, 6, 7, 8, 9])
print(s1.union(s2))
----

**교집합**

`&` 연산자를 사용해서 두 집합간의 교집합을 구할 수 있습니다.

[source, python]
----
s1 = set([1, 2, 3, 4, 5, 6])
s2 = set([4, 5, 6, 7, 8, 9])
print(s1 & s2)
----

----
{4, 5, 6}
----

intersection() 메소드를 사용해서 동일한 값을 구할 수 있습니다.

[source, python]
----
s1 = set([1, 2, 3, 4, 5, 6])
s2 = set([4, 5, 6, 7, 8, 9])
print(s1.intersection(s2))
----

----
{4, 5, 6}
----

**차집합**

`-` 연산자를 사용해서 두 집합간의 차집합을 구할 수 있습니다.

[source, python]
----
s1 = set([1, 2, 3, 4, 5, 6])
s2 = set([4, 5, 6, 7, 8, 9])
print(s1 - s2)
----

----
{1, 2, 3}
----

difference() 메소드를 사용해서 동일한 값을 구할 수 있습니다.

[source, python]
----
s1 = set([1, 2, 3, 4, 5, 6])
s2 = set([4, 5, 6, 7, 8, 9])
print(s1.difference(s2))
----

----
{1, 2, 3}
----

== set 수정

set 타입은 mutable 타입이므로 요소의 값을 수정하거나 요소를 삭제, 수정할 수 있습니다.

**요소 추가*

두 가지 방법으로 set에 요소를 추가할 수 있습니다. add() 메소드를 사용하여 해당 set 객체에 요소를 추가합니다.

[source, python]
----
s1 = set([1, 2, 3, 4, 5, 6])
s1.add(7)
----

update() 메소드를 사용하면 여러 요소를 set에 추가합니다.

[source, python]
----
s1 = set([1, 2, 3, 4, 5, 6])
s2 = set([4, 5, 6, 7, 8, 9])
s1.update(s2)
----

update 메소드를 사용하면 Sequence 타입 객체의 모든 요소 또한 추가할 수 있습니다.

[source, python]
----
s1 = set([1, 2, 3, 4, 5, 6])
s2 = set([4, 5, 6, 7, 8, 9])
s1.update("hello")
print(s1)
----

----
{1, 2, 3, 4, 5, 6, 'o', 'l', 'h', 'e'}
----

**요소 삭제**

remove() 메소드를 사용하여 요소를 삭제합니다.

[source, python]
----
s1 = set([1, 2, 3, 4, 5, 6])
s1.remove(1)
print(s1)
----

----
{2, 3, 4, 5, 6}
----

https://wikidocs.net/1015