= Dictionary 타입

* key-value로 이루어진 값을 저장
* key를 사용하여 value를 구하는 자료구조
* hashtable로 구현

---

dictionary는 쉼표( , ) 구분되는 key와 value를 한 쌍으로 가지는 목록을 저장하는 타입이며, dict 타입 객체입니다. key와 value는 콜론( : )으로 구분됩니다. 가변형(Immutable) 타입이며, Python 도움말(help 함수)에서 설명하는 tuple 타입의 개요는 아래와 같습니다.

----
class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
----

== Dictionary 생성

Dictionary는 중괄호( { } )를 사용하여 생성되며, 각 요소는 쉼표( , )로 구분됩니다. key와 value는 콜론( : )으로 구분됩니다. 아래 코드는 요소를 포함하지 않는 dictionary를 생성합니다.

[source, python]
----
dictionary = {}
----

아래 코드는 int 타입을 key로, 문자열을 value로 가지는 요소들을 포함하는 dictionary를 생성합니다.

[source, python]
----
dictionary = {1: "celine", 2: "jason"}
----

key와 value는 다른 타입으로 선언될 수 있습니다.

[source, python]
----
dictionary = {1: "celine", "gender": "female", "age": 32}
----

Immutable 타입은 key로 사용할 수 있으며, 모든 type을 value로 사용할 수 있습니다.

[source, python]
----
dictionary = {(1, "celine"): "Computer Science", "subjects": ["OS", "DB", "Python"]}
----

== 디스플레이(displey)

list, set, dictionary를 구성하기 위해, Python은 디스플레이(display)라고 부르는 특별한 문법을 가지고 있습니다. 디스플레이는 두 가지 스타일로 제공됩니다.

* list, set, dictionary 등 컨테이너의 내용을 명시적으로 나열 - list 생성
* 일련의 반복과 필터링 지시들을 통해 계산. 이를 Comprehenssion이라고 부름

Comprehenssion의 공통 문법 요소는 아래와 같습니다.

----
comprehension ::=  assignment_expression comp_for
comp_for      ::=  ["async"] "for" target_list "in" or_test [comp_iter]
comp_iter     ::=  comp_for | comp_if
comp_if       ::=  "if" or_test [comp_iter]
----

아래와 같은 Comprehenssion으로 리스트를 생성할 수 있습니다.

[source, python]
----
dic = {x:y for x,y in zip(range(5), range(10, 15))}
print(dic)
----

----
{0: 10, 1: 11, 2: 12, 3: 13, 4: 14}
----

== key를 사용해 dictionary 읽기

dictionary의 요소들은 key를 인덱스로 사용해서 읽을 수 있습니다. dictionary의 요소는 key를 이용해서만 값을 읽을 수 있으므로, 슬라이싱은 사용할 수 없습니다.

[source, python]
----
dict = {"celine": 1, "james": 3, "robert": 2}
print(dict["james"])
----

----
3
----

== 주의사항

dictionary에서 Key는 고유한 값이므로 중복되는 Key 값을 설정해 놓으면 하나를 제외한 나머지 것들이 모두 무시됩니다. 다음 예에서 볼 수 있듯이 동일한 Key가 2개 존재할 경우, 1: 'a' 쌍이 무시됩니다.

[source, python]
----
a = {1:'a', 1:'b'}
a
----

----
{1: 'b'}
----

== dictionary 메소드

**keys() 메소드**

dictionary 객체의 모든 key들로 구성된 dict_keys 타입 객체를 return 합니다.

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
print(dict.keys())
----

----
dict_keys(['number', 'name', 'gender', 'age'])
----

|===
|**참고** Python 2.7 까지는 keys() 함수가 list 타입 객체를 return 했습니다. Python 3.0 이상의 버전에서는 메모리 절약을 위해 dict_keys 타입 객체를 return 하도록 변경되었습니다. dict_keys 타입은 list와 비슷하지만 인덱싱과 슬라이싱을 할 수 없으며 변경, 추가도 할 수 없습니다. dict_keys는 list 함수의 파라미터로 list 타입 객체로 변환될 수 있습니다.
|===

**values() 메소드**

dictionary 객체의 모든 value들로 구성된 dict_values 타입 객체를 return 합니다.

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
print(dict.values())
----

----
dict_values([1, 'celine', 'female', 32])
----

**clear() 메소드**

dictionary 객체의 모든 key:value 쌍을 삭제합니다.

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
dict.clear()
print(dict)
----

----
{}
----

**get() 메소드**

key에 대응되는 value를 return 합니다. key를 사용해서 인덱싱 하는 것과 동일합니다.

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
print(dict.get("name"))
----

----
celine
----

dictionary에 없는 key를 사용해서 value를 검색하면 None을 반환합니다.

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
print(dict.get("department"))
----

dictionary에 key가 없을 경우 None이 아닌 값을 기본값으로 사용하자 할 경우, 두 개의 파라미터를 사용할 수 있습니다.

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
print(dict.get("department", "No affiliation"))
----

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
print(dict.get("department", "No affiliation"))
----

----
No affiliation
----

== 반복으로 dictionary 읽기

dictionary의 key:values 요소들은 반복해서 읽을 수 있습니다. 각 요소의 기본 값은 key입니다.

**key 읽기**

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
for e in dict:
    print(e)
----

----
number
name
gender
age
----

keys() 메소드를 호출한 dict_keys 타입 객체를 사용하여 객체내의 모든 key를 읽습니다.

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
for key in dict.keys():
    print(key)
----

----
number
name
gender
age
----

**value 읽기**

key를 인덱스로 사용해서 value를 읽을 수 있습니다.

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
for e in dict:
    print(dict[e])
----

----
1
celine
female
32
----

values() 메소드를 호출한 dict_values 타입 객체를 사용하여 객채내의 모든 value를 읽습니다.

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
for value in dict.values():
    print(value)
----

----
1
celine
female
32
----

**key, value 읽기**

items() 메소드를 사용하면 key, value를 모두 반환합니다.

[source, python]
----
dict = {"number": 1, "name": "celine", "gender": "female", "age": 32}
for key, value in dict.items():
    print(key, ":", value)
----

----
number : 1
name : celine
gender : female
age : 32
----