= Python 소개

* 웹 애플리케이션, 소프트웨어 개발, 데이터 과학, 머신 러닝등에 널리 사용되는 프로그래밍 언어
* 여러 플랫폼과 운영체제에서 실행되는 멀티 플랫폼 환경
* 높은 생산성을 가지는 프로그래밍 환경 및 배포 환경 제공
* 다양한 유형의 시스템과 원활하게 통합

---

Python은 웹 애플리케이션, 소프트웨어 개발, 데이터 과학, 기계 학습에 널리 사용되는 프로그래밍 언어입니다. Python은 효율적이고, 배우기 쉬우며, 여러 플랫폼에서 실행될 수 있습니다.

**Python의 이점**

* Python 프로그램은 기본적이고 영어와 유사한 구문을 가지고 있기 때문에 개발자가 쉽게 읽고 이해할 수 있습니다. 
* Python은 다른 많은 언어에 비해 더 적은 코드 줄을 사용하여 Python 프로그램을 작성할 수 있기 때문에 개발자의 생산성을 높입니다.
* Python에는 거의 모든 작업에 재사용 가능한 코드가 포함된 대규모 표준 라이브러리가 있습니다. 결과적으로 개발자는 코드를 처음부터 작성할 필요가 없습니다.
* 개발자는 Java, C 및 C++ 등의 다른 인기 있는 프로그래밍 언어와 함께 Python을 쉽게 사용할 수 있습니다.
* 활발한 Python 커뮤니티는 전 세계 수백만 명의 개발자가 지원하고 있습니다. 문제가 발생하면 커뮤니티에서 빠른 지원을 받을 수 있습니다.
* 동영상, 자습서, 문서 및 개발자 가이드등의 Python 프로그래밍에 필요한 다양한 리소스를 쉽게 찾을 수 있습니다.
* Python은 Windows, macOS, Linux 및 Unix와 같은 다양한 컴퓨터 운영 체제에서 호환 가능합니다.

**Python의 활용**

Python 언어에는 다음 예제를 포함하여 애플리케이션 개발의 여러 사용 사례가 있습니다.

** 서버 사이드  웹 개발 +
서버 사이드 웹 개발에는 웹 사이트가 사용자에게 정보를 표시하기 위해 수행하는 복잡한 백엔드 기능이 포함됩니다. 예를 들어 웹 사이트는 데이터베이스와의 상호 작용, 다른 웹 사이트와의 통신, 네트워크를 통해 전송되는 데이터 보호가 필요합니다. +
Python은 복잡한 백엔드 기능을 위해 미리 작성된 코드로 구성된 많은 라이브러리를 제공하기 때문에 서버 측 코드를 작성하는 데 유용합니다. 또한 개발자는 웹 애플리케이션을 더 빠르고 쉽게 구축하는 데 필요한 모든 도구를 제공하는 광범위한 Python 프레임워크를 사용합니다. 예를 들어, 개발자는 코드를 처음부터 작성할 필요가 없기 때문에 몇 초 만에 웹 애플리케이션의 뼈대를 만들 수 있습니다. 그런 다음 외부 테스트 도구에 의존하지 않고 프레임워크의 테스트 도구를 사용하여 테스트할 수 있습니다. 
** Python 스크립트를 사용한 자동화 +
스크립팅 언어는 인간이 일반적으로 수행하는 작업을 자동화하는 프로그래밍 언어입니다. 프로그래머는 Python 스크립트를 폭넓게 사용하여 다음과 같은 일상적인 작업을 자동화합니다.
*** 한 번에 많은 파일 이름 변경
*** 파일을 다른 파일 형식으로 변환
*** 텍스트 파일에서 중복 단어 제거
*** 기본적인 수학 연산 수행
*** 이메일 메시지 전송
*** 콘텐츠 다운로드
*** 기본 로그 분석 수행
*** 여러 파일에서 오류 찾기
** 데이터 과학 및 기계 학습 +
데이터 과학은 데이터에서 귀중한 지식을 추출하고, 기계 학습(ML)은 컴퓨터가 데이터에서 자동으로 학습하고 정확한 예측을 하도록 가르칩니다. 데이터 사이언티스트는 다음과 같은 데이터 과학 작업에 Python을 사용합니다.
*** 데이터 전처리
**** 잘못된 데이터 수정 및 제거(데이터 정리) 
**** 데이터의 다양한 특징 추출 및 선택
**** 데이터 레이블링(데이터에 대한 의미 있는 이름 추가)
**** 데이터에서 여러 통계 찾기
**** 꺾은선 차트, 막대 그래프, 히스토그램, 파이 차트 등의 차트 및 그래프를 사용하여 데이터 시각화
*** 머신 러닝 +
데이터 사이언티스트는 Python ML 라이브러리를 사용하여 ML 모델을 훈련하고, 데이터를 정확하게 분류하는 분류자를 구축합니다. 다양한 분야의 사람들이 Python 기반 분류자를 사용하여 이미지, 텍스트 및 네트워크 트래픽 분류, 음성 인식, 얼굴 인식과 같은 분류 작업을 수행합니다. 데이터 사이언티스트는 고급 ML 기술인 딥 러닝에도 Python을 사용합니다.

** 소프트웨어 개발 +
소프트웨어 개발자는 다음과 같은 다양한 개발 작업 및 소프트웨어 애플리케이션에 Python을 사용하곤 합니다.
*** 소프트웨어 코드의 버그 추적
*** 소프트웨어 자동 구축
*** 소프트웨어 프로젝트 관리 처리
*** 소프트웨어 프로토타입 개발
*** 그래픽 사용자 인터페이스(GUI) 라이브러리를 사용하여 데스크톱 애플리케이션 개발
*** 단순한 텍스트 기반 게임을 보다 복잡한 비디오 게임으로 개발

** 소프트웨어 테스트 자동화 +
소프트웨어 테스팅은 소프트웨어의 실제 결과가 예상 결과와 일치하여 소프트웨어에 오류가 없는지 확인하는 프로세스입니다. 

*** Unittest, Robot 및 PyUnit과 같은 Python 단위 테스트 프레임워크를 사용하여 작성 중인 기능을 테스트할 수 있습니다. 
*** Python을 사용하여 다양한 테스트 시나리오에 대한 테스트 사례를 작성할 수 있습니다. 
*** 개발자는 여러 CI/CD 도구를 사용하여 테스트 스크립트를 자동으로 실행할 수 있습니다. 소프트웨어 테스터와 개발자는 Travis CI 및 Jenkins와 같은 CI/CD 도구를 사용하여 테스트를 자동화합니다. CI/CD 도구는 Python 테스트 스크립트를 자동으로 실행하고, 개발자가 새로운 코드 변경 사항을 도입할 때마다 테스트 결과를 보고합니다.