= Python 프로그래밍 언어

* 배우기 쉬우면서도 강력한 프로그래밍 언어
* 효율적인 자료구조와 객체지향 프로그래밍에 대한 간단하면서 효율적인 접근법 제공
* 우아한 문법과 Dynamic Typing(동적 타이핑) 지원
* 인터프리터 언어
* 대부분의 플랫폼과 문제 영역에서 스크립트 작성과 빠른 응용 프로그램 개발 환경 제공
* 고수준 데이터 타입들로 인해 복잡한 expression을 한 statement로 표현
* statement의 묶음은 괄호 대신 들여쓰기(indentation)로 표현
* variable이나 argument의 선언이 필요 없음

---

컴퓨터를 많이 사용한다면, 자동화하고 싶은 작업을 발견하게 됩니다. 예를 들어, 텍스트 파일들을 검색하여 수정하고 싶거나, 사진 파일들을 복잡한 방법으로 이름을 바꾸거나 정렬할 수 있습니다. 작은 데이터베이스나 GUI 응용 프로그램 또는 간단한 게임을 만들고 싶을 수도 있습니다.

전문 개발자라면, C/C++/Java 라이브러리로 작업해야만 할 수 있는데, 일반적인 코드 작성/컴파일/재컴파일 순환이 너무 느리다는 것을 깨닿게 될 수도 있습니다. 작성한 라이브러리들을 위한 테스트 묶음을 작성할 때는 테스트를 위한 코드 작성이 지겨워 질 수도 있습니다. 또는 확장 언어를 사용하는 프로그램을 작성했는데, 새로운 언어 전체를 구현하고 싶지 않을 수 있습니다.

Python은 바로 이런 경우를 위한 프로그래밍 언어입니다.

이런 작업 중 일부를 위해 Unix 쉘 스크립트나 Windows 배치 파일을 작성할 수 있지만 쉘 스크립트는 파일 이동 및 텍스트 데이터 변경에 가장 적합하며 GUI 애플리케이션이나 게임에는 적합하지 않을 수 있습니다. C/C++/Java 프로그램을 작성할 수 있지만 첫 번째 프로그램에 대한 초안을 작성하는데도 개발 시간이 많이 걸릴 수 있습니다. Python은 사용이 더 간단하고 Windows, macOS 및 UNIX 운영체제에서 사용할 수 있으며 작업을 더 빠르게 완료하는데 도움이 됩니다.

Python은 사용이 간단하지만, 제대로 갖춰진 프로그래밍 언어입니다. 쉘 스크립트나 배치 파일보다 더 많은 구조를 제공하고 커다란 프로그램을 위한 지원을 제공합니다. 반면에, Python은 C보다 훨씬 많은 오류 검사를 제공하고, 유연한 배열과 딕셔너리 같은 고수준의 데이터 타입들을 내장하고 있습니다. 더 일반적인 데이터 타입들 때문에 AWK나 Perl 보다 많은 문제 영역에서 사용할 수 있는데, 그러면서도 여전히 많은 것들이 적어도 이들 언어를 사용하는 것 만큼 Python에서도 쉽게 해결할 수 있습니다.

Python은 프로그램을 여러 모듈로 나눌 수 있다고 하는데, 각 모듈은 다른 파이썬 프로그램에서 재사용할 수 있습니다. 대규모의 표준 모듈들이 따라오는데 이를 기초 프로그램으로 사용하거나 Python을 배우기 위한 예제로 활용할 수 있습니다. 이 모듈에는 파일 입출력, 시스템 호출, 소켓들이 포함되는데, TK와 같은 GUI 도구상자에 대한 인터페이스도 들어 있습니다.

Python은 인터프리터 언어입니다. 컴파일과 링크 단계가 필요 없으므로 개발 시간을 상당히 단축해 줍니다. 인터프리터는 대화형으로 사용할 수 있어서, 언어의 기능을 실험하거나 쓰고 버릴 프로그램을 만들거나, 바닥부터 프로그램을 만들어가는 동안 함수들을 테스트하기 쉽습니다. 간편한 계산기로도 쓸 수 있습니다.

Python은 간결하고 읽기 쉽게 프로그램을 작성할 수 있도록 합니다. Python 프로그램은 여러 가지 이유로 가튼 기능의 C, C++, Java 프로그램에 비해 간결합니다.

* 고수준 데이터 타입들로 인해 복잡한 expression을 한 statement로 표현할 수 있습니다.
* statement의 묶음은 괄호 대신 들여쓰기(indentation)로 표현합니다.
* variable이나 argument의 선언이 필요 없습니다.

Python은 확장 가능 합니다. C로 프로그램하는 법을 안다면, 인터프리터에 새로운 내장 함수나 자료형을 추가해서, 핵심 연산을 최대 속도로 수행하거나 바이너리 형태로만 제공되는 라이브러리(가령 업체가 제공하는 그래픽스 라이브러리)에 파이썬 프로그램을 연결할 수 있습니다. 진짜 파이썬에 매료되었다면, C로 만든 응용 프로그램에 파이썬 인터프리터를 연결하여 그 응용 프로그램의 확장이나 명령 언어로 사용할 수 있습니다.

파이썬 이라는 이름은 “Monty Python's Flying Circus”라는 BBC 쇼에서 따온 것이고, 파충류와는 아무런 관련이 없습니다. 문서에서 Monty Python의 농담을 인용하는 것은 허락된 것일 뿐만 아니라, 권장되고 있습니다.

Python은 배우기 쉬우면서도 강력한 프로그래밍 언어입니다. 효율적인 자료구조와 객체지향 프로그래밍에 대한 간단하고도 효율적인 접근법을 제공합니다. Python은 우아한 문법과 dynamic typing을 지원하는 인터프리터 언어로서, 대부분의 플랫폼과 문제 영역에서 스크립트 작성과 빠른 응용 프로그램 개발에 이상적인 환경을 제공합니다.

Python 인터프리터와 광범위한 표준 라이브러리는 link:https://https://www.python.org/[Python 웹 사이트]에서 주요 플랫폼에 대한 소스코드 또는 바이너리 형식으로 제공되며 자유롭게 배포할 수 있습니다. Python 웹 사이트에는 무료로 제공되는 많은 서드파티 Python 모듈, 추가 문서들이 제공됩니다.

Python 인터프리터는 C, C++(또는 C에서 호출 가능한 다른 언어들)로 구현된 새 함수나 자료구조를 쉽게 추가할 수 있습니다. 파이썬은 응용 프로그램을 위한 확장 언어로도 적합합니다.

link:./03_introduction_to_python.adoc[이전: Python 소개] +
link:./05_python_runtime.adoc[다음: Python 실행 환경]