= Python의 역사

* 1980년 후반에 고안
* 1991년 귀도 반 로섬에 의해 구현됨
* 1994년 버전 1 개발, 배포
* 2000년 버전 2 개발, 배포
* 2008년 버전 3 개발, 배포

---

프로그래밍 언어 Python은 1980년대 후반에 고안되었으며 1989년 12월에 네덜란드 의 CWI 에서 Guido van Rossum 이 Amoeba 운영 체제 와 예외 처리 및 인터페이스가 가능한 ABC 의 후속 버전으로 구현을 시작 했습니다.  Van Rossum은 Python의 주요 저자이며 Python의 방향을 결정하는 데 있어 그의 지속적인 중심 역할은 Python 커뮤니티에서 그에게 준 Benevolent Dictator for Life (BDFL)라는 칭호에 반영되어 있습니다.(그러나 Van Rossum은 2018년 7월 12일에 리더에서 물러났습니다.). Python은 BBC TV 쇼 Monty Python's Flying Circus 에서 이름을 따왔습니다.

Python 2.0은 2000년 10월 16일에 출시되었으며, 메모리 관리를 위한 사이클 감지 가비지 수집기 및 유니코드 지원 과 더불어 보다 투명하고 커뮤니티 지원 프로세스로의 전환을 포함한 많은 주요 새로운 기능이 추가되었습니다.

Python 3.0은 주요 이전 버전과 호환되지 않는 릴리스로, 장기간의 테스트 끝에 2008년 12월 3일에 출시되었습니다. 주요 ​​기능 중 다수도 이전 버전과 호환되지만 현재는 지원되지 않는 Python 2.6 및 2.7로 백포트 되었습니다.

== 초기

1991년 2월, Van Rossum은 코드(버전 0.9.0이라는 라벨이 붙음)를 alt.sources에 게시했습니다. 이 개발 단계에서는 상속, 예외 처리, 함수 및 핵심 데이터 유형, 등 이 있는 클래스 가 이미 존재 했습니다 .list 또한 이 초기 릴리스에는 Modula-3에서 차용한 모듈 시스템이 있었습니다 .Van Rossum 은 이 모듈 을 "Python의 주요 프로그래밍 단위 중 하나"라고 설명합니다. Python의 예외 모델은 절이 추가되어 Modula-3와 유사합니다. 1994년에 Python의 주요 토론 포럼 인 comp.lang.python이 형성되어 Python 사용자 기반과 인기의 성장에 있어 이정표를 세웠습니다.

== 버전 1

Python은 1994년 1월에 버전 1.0에 도달했습니다. 이 릴리스에는 함수형 프로그래밍 도구인 lambda, map, filter 기능이 포함되었습니다.

Van Rossum이 CWI에 있는 동안 출시된 마지막 버전은 Python 1.2였습니다. 1995년 Van Rossum은 버지니아 주 레스톤 에 있는 National Research Initiatives Corporation (CNRI) 에서 Python 작업을 계속했고, 그곳에서 여러 버전을 출시했습니다.

버전 1.4에서 Python은 여러 가지 새로운 기능을 획득했습니다. 이 중 주목할 만한 것은 Modula-3에서 영감을 받은 키워드 인수 ( Common Lisp 의 키워드 인수 와도 유사 )와 복소수 에 대한 기본 지원입니다. 또한 이름 망글링을 통한 기본적인 형태의 데이터 숨김 도 포함되어 있지만 , 이는 쉽게 우회할 수 있습니다.

Van Rossum이 CNRI에 있는 동안 그는 모든 사람을 위한 컴퓨터 프로그래밍(CP4E) 이니셔티브를 시작하여 대부분의 고용주가 요구하는 기본적인 영어 문해력과 수학 능력과 유사한 프로그래밍 언어에 대한 기본적인 "문해력"을 갖춘 더 많은 사람들이 프로그래밍에 더 쉽게 접근할 수 있도록 하려고 했습니다. Python은 여기에서 중심적인 역할을 했습니다. 깔끔한 구문에 초점을 맞추었기 때문에 이미 적합했고 CP4E의 목표는 이전 프로젝트인 ABC와 유사했습니다. 이 프로젝트는 DARPA 에서 자금을 지원했습니다. 2007년 현재 CP4E 프로젝트는 비활성 상태이며 Python은 구문과 의미에서 쉽게 배울 수 있고 너무 난해하지 않으려고 하지만 프로그래머가 아닌 사람들에게 다가가는 데는 적극적인 관심이 없습니다.

== 버전 2

2000년 10월에 출시된 Python 2.0은 함수형 프로그래밍 언어 SETL 과 Haskell 에서 차용한 기능인 list comprehensions를 도입했습니다. 이 구조에 대한 Python의 구문은 Haskell과 매우 유사하지만 Haskell은 구두점을 선호 하고 Python은 알파벳 키워드를 선호합니다. Python 2.0은 또한 참조 주기를 수집할 수 있는 가비지 수집기를 도입했습니다.

Python 2.1은 Python 1.6.1과 Python 2.0에 가까웠습니다. 라이선스가 Python Software Foundation License 로 변경되었습니다 . Python 2.1 알파 릴리스 이후 추가된 모든 코드, 문서 및 사양은 Apache Software Foundation을 모델로 하여 2001년에 설립된 비영리 조직인 Python Software Foundation (PSF) 이 소유합니다. 이 릴리스에는 다른 정적 범위 언어 와 마찬가지로 중첩 범위를 지원하기 위해 언어 사양이 변경되었습니다.

Python 2.2는 2001년 12월에 출시되었습니다. 주요 ​​혁신은 Python의 유형( C 로 작성된 유형 )과 클래스(Python으로 작성된 유형)를 하나의 계층으로 통합한 것입니다. 이 단일 통합으로 인해 Python의 객체 모델이 순수하고 일관되게 객체 지향적이 되었습니다. 또한 Icon 에서 영감을 받은 Generator도 추가되었습니다 .

Python 2.5는 2006년 9월에 출시되었으며 with 컨텍스트 관리자 내에서 코드 블록을 묶는 명령문을 도입했습니다 (예: 코드 블록이 실행되기 전에 잠금을 취득한 후 잠금을 해제하거나 파일을 열고 닫기). 이를 통해 리소스 취득 초기화 (RAII)와 유사한 동작이 허용되고 일반적인 try/finally 관용구를 대체합니다.

Python 2.6은 Python 3.0과 동시에 출시되었으며 해당 릴리스의 일부 기능과 Python 3.0에서 제거된 기능의 사용을 강조하는 "경고" 모드를 포함했습니다. 마찬가지로 Python 2.7은 2009년 6월 26일에 출시된 Python 3.1과 동시에 출시되었으며 해당 기능을 포함했습니다. 그 후 Parallel 2.x 및 3.x 릴리스는 중단되었고 Python 2.7은 2.x 시리즈의 마지막 릴리스였습니다. 2014년 11월에 Python 2.7이 2020년까지 지원될 것이라고 발표되었지만 사용자는 가능한 한 빨리 Python 3으로 이동하도록 권장되었습니다. Python 2.7 지원은 2020년 1월 1일에 2.7 개발 브랜치의 코드 동결 과 함께 종료되었습니다 . 최종 릴리스인 2.7.18은 2020년 4월 20일에 출시되었으며 여기에는 중요한 버그와 릴리스 차단 요소에 대한 수정 사항이 포함되었습니다. 이로써 Python 2의 수명 종료가 이루어졌습니다.

== 버전 3

Python 3.0(또한 "Python 3000" 또는 "Py3K"라고도 함)은 2008년 12월 3일에 출시되었습니다. 이것은 언어의 근본적인 설계 결함을 바로잡기 위해 설계되었습니다. 필요한 변경 사항은 2.x 시리즈와의 완전한 하위 호환성을 유지하면서 구현할 수 없었기 때문에 새로운 주요 버전 번호가 필요했습니다. Python 3의 지침 원칙은 "이전 작업 방식을 제거하여 기능 중복을 줄이는 것"이었습니다.

Python 3.0은 이전 버전과 동일한 철학으로 개발되었습니다. 그러나 Python은 동일한 작업을 프로그래밍하는 새롭고 중복된 방법을 축적했기 때문에 Python 3.0은 Python의 선(Zen)에 따라 중복되는 구성 요소와 모듈을 제거하는 데 중점을 두었습니다 . "그것을 하는 데는 하나의 분명한 방법이 있어야 하며, 바람직하게는 오직 하나의 방법이 있어야 합니다."

그럼에도 불구하고 Python 3.0은 다중 패러다임 언어로 남았습니다. 코더는 여전히 객체 지향, 구조화, 함수형 프로그래밍 패러다임을 따를 수 있었지만, 이처럼 광범위한 선택 범위 내에서 세부 사항은 Python 2.x보다 Python 3.0에서 더 명확하게 표현되도록 의도되었습니다.

link:./09_module.adoc[이전: 모듈] +
link:./12_lab1-1_install_anaconda.adoc[다음: Lab 1-1 Anaconda 설치]